import Link from "next/link";
import { redirect } from "next/navigation";
import { Award, Users, UserRound, Settings, Shield, ToggleLeft, Megaphone, Timer, WalletCards } from "lucide-react";
import ProFeatureLock from "@/components/billing/ProFeatureLock";
import PageHero from "@/components/ui/PageHero";
import { createClient } from "@/lib/supabase/server";
import { getAuthContext } from "@/lib/auth/context";
import { AUTH_ROUTES } from "@/lib/auth/routes";
import { getClubBillingAccess } from "@/lib/billing/club-billing";
import { getServerI18n } from "@/lib/i18n/server";
import { translate } from "@/lib/i18n/messages";
import type { AppLocale } from "@/lib/i18n/config";


type ClubRow={id:string;display_name:string|null;primary_color:string|null};
function isAdminRole(role:string|null|undefined){return role==="admin";}
function getRoleLabel({role,isPowerUser,memberLabel}:{role:string|null|undefined;isPowerUser:boolean;memberLabel:string}){if(isPowerUser)return "Power User";if(role==="admin")return "Admin";return memberLabel;}
type AdminCardProps={href:string;eyebrow:string;title:string;description:string;icon:React.ReactNode;openLabel:string};
function AdminCard({href,eyebrow,title,description,icon,openLabel}:AdminCardProps){return <Link href={href} className="group rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div className="flex-1"><div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-400">{eyebrow}</div><h2 className="mt-2 text-lg font-semibold text-slate-950">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></div><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100 text-slate-700">{icon}</div></div><div className="mt-5 flex items-center text-sm font-medium text-slate-900">{openLabel}<span className="ml-2 transition group-hover:translate-x-1">→</span></div></Link>}
function ProStatusPanel({clubName,isPro,locale}:{clubName:string;isPro:boolean;locale:AppLocale}){const t=(key:Parameters<typeof translate>[1],params?:Record<string,string|number|null|undefined>)=>translate(locale,key,params);if(!isPro)return <ProFeatureLock clubName={clubName} title={t("admin.proTitle")} description={t("admin.proDescription")} featureList={[t("admin.proFeatureStats"),t("admin.proFeatureStandings"),t("admin.proFeatureMvp"),t("admin.proFeatureShare")]} compact/>;return <div className="rounded-[24px] border border-emerald-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="inline-flex rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800">{t("admin.proActive")}</div><h2 className="mt-3 text-lg font-extrabold tracking-tight text-slate-950">{t("admin.proUnlocked",{club:clubName})}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{t("admin.proUnlockedText")}</p></div><Link href="/power-user/clubs" className="inline-flex items-center justify-center rounded-2xl border border-slate-200 bg-slate-950 px-4 py-3 text-sm font-bold text-white">{t("admin.checkBilling")}</Link></div></div>}

export default async function AdminPage(){
 const {locale,t}=await getServerI18n();
 const ctx=await getAuthContext(); if(!ctx.user)redirect(AUTH_ROUTES.login); if(!ctx.activeClubId)redirect(AUTH_ROUTES.selectClub); const membership=ctx.memberships.find(i=>i.club_id===ctx.activeClubId)??null; if(!(ctx.isPowerUser||isAdminRole(membership?.role)))redirect(AUTH_ROUTES.dashboard); const supabase=await createClient(); const [{data:clubData,error:clubError},billingAccess]=await Promise.all([supabase.from("clubs").select("id, display_name, primary_color").eq("id",ctx.activeClubId).maybeSingle<ClubRow>(),getClubBillingAccess(supabase,ctx.activeClubId)]); if(clubError)throw new Error(`Der aktive Club konnte nicht geladen werden: ${clubError.message}`); if(!clubData)redirect(AUTH_ROUTES.dashboard); const club=clubData as ClubRow; const clubName=club.display_name?.trim()||t("admin.yourTeam"); const roleLabel=getRoleLabel({role:membership?.role,isPowerUser:ctx.isPowerUser,memberLabel:t("admin.roleMember")});
 return <main className="min-h-screen bg-neutral-100"><section className="mx-auto flex w-full max-w-6xl flex-col gap-4 px-4 py-4 sm:px-6 lg:px-8">
  <PageHero primaryColorKey={club.primary_color} eyebrow={t("admin.eyebrow")} title={clubName} description={t("admin.description")} backLabel={t("admin.back")} backHref="/" topRightSlot={<div className="inline-flex min-h-7 items-center justify-center rounded-full border border-white/10 bg-white/10 px-2.5 py-1 text-[10px] font-semibold text-white/88">{roleLabel}</div>} actionsSlot={ctx.isPowerUser?<div className="inline-flex min-h-7 items-center justify-center rounded-full border border-sky-200/30 bg-sky-400/10 px-2.5 py-1 text-[10px] font-semibold text-sky-100">{t("admin.powerMode")}</div>:null} compact/>
  {billingAccess.isFreeLaunch?<div className="rounded-[24px] border border-sky-200 bg-sky-50 p-4 shadow-sm"><div className="inline-flex rounded-full border border-sky-200 bg-white px-3 py-1 text-xs font-bold text-sky-800">{t("admin.freeLaunch")}</div><h2 className="mt-3 text-lg font-extrabold tracking-tight text-slate-950">{t("admin.allUnlocked",{club:clubName})}</h2><p className="mt-1 text-sm leading-6 text-slate-700">{t("admin.allUnlockedText")}</p></div>:billingAccess.isPro?null:<ProStatusPanel clubName={clubName} isPro={billingAccess.isPro} locale={locale}/>} 
  <div className="grid gap-4 md:grid-cols-2">
   <AdminCard href="/admin/members" eyebrow={t("admin.membersEyebrow")} title={t("admin.membersTitle")} description={t("admin.membersDescription")} openLabel={t("admin.open")} icon={<Users className="h-6 w-6" strokeWidth={2.1}/>}/>
   <AdminCard href="/admin/players" eyebrow={t("admin.gameEyebrow")} title={t("admin.rosterTitle")} description={t("admin.rosterDescription")} openLabel={t("admin.open")} icon={<UserRound className="h-6 w-6" strokeWidth={2.1}/>}/>
   <AdminCard href="/admin/game-timer" eyebrow={t("admin.trainingEyebrow")} title={t("admin.timerTitle")} description={t("admin.timerDescription")} openLabel={t("admin.open")} icon={<Timer className="h-6 w-6" strokeWidth={2.1}/>}/>
   <AdminCard href="/admin/announcements" eyebrow={t("admin.communicationEyebrow")} title={t("admin.announcementTitle")} description={t("admin.announcementDescription")} openLabel={t("admin.open")} icon={<Megaphone className="h-6 w-6" strokeWidth={2.1}/>}/>
   <AdminCard href="/mannschaftskasse" eyebrow={t("admin.teamLifeEyebrow")} title={t("admin.cashboxTitle")} description={t("admin.cashboxDescription")} openLabel={t("admin.open")} icon={<WalletCards className="h-6 w-6" strokeWidth={2.1}/>}/>
   <AdminCard href="/admin/settings" eyebrow={t("admin.settingsEyebrow")} title={t("admin.settingsTitle")} description={t("admin.settingsDescription")} openLabel={t("admin.open")} icon={<Settings className="h-6 w-6" strokeWidth={2.1}/>}/>
   {ctx.isPowerUser?<><AdminCard href="/power-user" eyebrow="Power User" title="Power User Dashboard" description={t("admin.powerDashboardDescription")} openLabel={t("admin.open")} icon={<Shield className="h-6 w-6" strokeWidth={2.1}/>}/><AdminCard href="/power-user/badges" eyebrow="Power User" title={t("admin.badgeCatalog")} description={t("admin.badgeCatalogDescription")} openLabel={t("admin.open")} icon={<Award className="h-6 w-6" strokeWidth={2.1}/>}/><AdminCard href="/power-user/flags" eyebrow="Power User" title={t("admin.featureFlags")} description={t("admin.featureFlagsDescription")} openLabel={t("admin.open")} icon={<ToggleLeft className="h-6 w-6" strokeWidth={2.1}/>}/></>:null}
  </div>
 </section></main>;
}
