import Link from "next/link";
import { redirect } from "next/navigation";
import {
  Users,
    Mail,
      UserRound,
        Palette,
          CalendarRange,
            Shield,
              ToggleLeft,
              } from "lucide-react";
              import { createClient } from "@/lib/supabase/server";
              import { requireClub } from "@/lib/auth/guards";
              import { AUTH_ROUTES } from "@/lib/auth/routes";
              import { isFounderEmail } from "@/lib/auth/founder";

              type ClubRow = {
                id: string;
                  display_name: string | null;
                  };

                  function isAdminRole(role: string | null | undefined) {
                    return role === "admin" || role === "owner";
                    }

                    function getRoleLabel(role: string | null | undefined) {
                      if (role === "owner") return "Owner";
                        if (role === "admin") return "Admin";
                          return "Mitglied";
                          }

                          type AdminCardProps = {
                            href: string;
                              eyebrow: string;
                                title: string;
                                  description: string;
                                    icon: React.ReactNode;
                                    };

                                    function AdminCard({
                                      href,
                                        eyebrow,
                                          title,
                                            description,
                                              icon,
                                              }: AdminCardProps) {
                                                return (
                                                    <Link
                                                          href={href}
                                                                className="group rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"
                                                                    >
                                                                          <div className="flex items-start justify-between gap-4">
                                                                                  <div className="flex-1">
                                                                                            <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-400">
                                                                                                        {eyebrow}
                                                                                                                  </div>
                                                                                                                            <h2 className="mt-2 text-lg font-semibold text-slate-950">{title}</h2>
                                                                                                                                      <p className="mt-2 text-sm leading-6 text-slate-600">{description}</p>
                                                                                                                                              </div>

                                                                                                                                                      <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100 text-slate-700">
                                                                                                                                                                {icon}
                                                                                                                                                                        </div>
                                                                                                                                                                              </div>

                                                                                                                                                                                    <div className="mt-5 flex items-center text-sm font-medium text-slate-900">
                                                                                                                                                                                            Öffnen
                                                                                                                                                                                                    <span className="ml-2 transition group-hover:translate-x-1">→</span>
                                                                                                                                                                                                          </div>
                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                );
                                                                                                                                                                                                                }

                                                                                                                                                                                                                export default async function AdminPage() {
                                                                                                                                                                                                                  const { clubId, membership } = await requireClub();

                                                                                                                                                                                                                    if (!isAdminRole(membership.role)) {
                                                                                                                                                                                                                        redirect(AUTH_ROUTES.dashboard);
                                                                                                                                                                                                                          }

                                                                                                                                                                                                                            const supabase = await createClient();

                                                                                                                                                                                                                              const [{ data: clubData, error: clubError }, authResult] = await Promise.all([
                                                                                                                                                                                                                                  supabase
                                                                                                                                                                                                                                        .from("clubs")
                                                                                                                                                                                                                                              .select("id, display_name")
                                                                                                                                                                                                                                                    .eq("id", clubId)
                                                                                                                                                                                                                                                          .maybeSingle(),
                                                                                                                                                                                                                                                              supabase.auth.getUser(),
                                                                                                                                                                                                                                                                ]);

                                                                                                                                                                                                                                                                  if (clubError) {
                                                                                                                                                                                                                                                                      throw new Error(
                                                                                                                                                                                                                                                                            `Der aktive Club konnte nicht geladen werden: ${clubError.message}`
                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                    const club = (clubData ?? null) as ClubRow | null;
                                                                                                                                                                                                                                                                                      const clubName = club?.display_name?.trim() || "Dein Team";
                                                                                                                                                                                                                                                                                        const roleLabel = getRoleLabel(membership.role);
                                                                                                                                                                                                                                                                                          const userEmail = authResult.data.user?.email ?? null;
                                                                                                                                                                                                                                                                                            const founderAccess = isFounderEmail(userEmail);

                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                  <main className="min-h-screen bg-neutral-100">
                                                                                                                                                                                                                                                                                                        <section className="mx-auto flex w-full max-w-6xl flex-col gap-5 px-4 py-4 sm:px-6 lg:px-8">
                                                                                                                                                                                                                                                                                                                <div className="flex items-center">
                                                                                                                                                                                                                                                                                                                          <Link
                                                                                                                                                                                                                                                                                                                                      href="/"
                                                                                                                                                                                                                                                                                                                                                  className="inline-flex items-center justify-center rounded-xl border border-black/10 bg-white px-4 py-2.5 text-sm font-semibold text-slate-900 transition hover:border-slate-900/20"
                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                        ← Zurück zur Startseite
                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                  <div className="rounded-[32px] border border-slate-200 bg-white p-6 shadow-sm sm:p-7">
                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="max-w-3xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-sm font-semibold uppercase tracking-[0.2em] text-slate-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      Adminbereich
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {clubName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="mt-3 text-sm leading-6 text-slate-600 sm:text-base">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Hier verwaltest du die wichtigsten Einstellungen für dein Team:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Spieler, Mitglieder, Club-Auftritt und Saisonlogik.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="rounded-3xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-emerald-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-sm font-medium">Deine Rolle</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-1 text-2xl font-bold">{roleLabel}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid gap-4 md:grid-cols-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <AdminCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/admin/members"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        eyebrow="Mitglieder"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title="Mitgliederverwaltung"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description="Sieh bestehende Mitglieder, aktuelle Rollen und Spieler-Verknüpfungen. Hier kannst du Rollen sicher zwischen Mitglied und Admin ändern."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            icon={<Users className="h-6 w-6" strokeWidth={2.1} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <AdminCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/admin/invites"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        eyebrow="Einladungen"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title="Einladungen verwalten"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description="Erstelle neue Einladungen und behalte im Blick, welche Zugänge noch offen oder aktiv sind."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            icon={<Mail className="h-6 w-6" strokeWidth={2.1} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <AdminCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/admin/players"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        eyebrow="Spielbetrieb"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title="Spieler & Team-Generator"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description="Pflege Spielerprofile, Positionen, Kategorien und Stärken und prüfe die Grundlagen für faire Teamaufteilungen."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            icon={<UserRound className="h-6 w-6" strokeWidth={2.1} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <AdminCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/admin/club"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        eyebrow="Branding"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title="Club & Branding"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description="Hinterlege Teamname, Logo und weitere sichtbare Club-Informationen für eine saubere Identität in der App."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            icon={<Palette className="h-6 w-6" strokeWidth={2.1} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <AdminCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/admin/seasons"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        eyebrow="Saison"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title="Saison-Einstellungen"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description="Lege fest, wie die Saison heißt und ab welchem Datum sie beginnt, damit Tabellen und Auswertungen sauber zugeordnet werden."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            icon={<CalendarRange className="h-6 w-6" strokeWidth={2.1} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {founderAccess ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <AdminCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          href="/founder"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          eyebrow="Founder"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title="Founder Dashboard"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          description="Globale KPIs über Clubs, User, Registrierungen und Trainings. Zentrale Sicht auf die Entwicklung von Strikr."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          icon={<Shield className="h-6 w-6" strokeWidth={2.1} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <AdminCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href="/founder/flags"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      eyebrow="Founder"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title="Feature Flags"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      description="Steuere neue Features gezielt pro Club oder schalte sie gesammelt für alle Clubs frei."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      icon={<ToggleLeft className="h-6 w-6" strokeWidth={2.1} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : null}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }