import Link from "next/link";
import { redirect } from "next/navigation";
import { requireClub } from "@/lib/auth/guards";
import { canManageClub } from "@/lib/auth/access";
import { createClient } from "@/lib/supabase/server";
import { getFeatureFlagsForClub } from "@/lib/feature-flags";
import { addPenaltyAction,deletePenaltyAction,reopenPenaltyAction,resolvePenaltyAction } from "./actions";

type Props={searchParams?:Promise<{saved?:string;error?:string}>};
type Player={id:number;name:string|null;first_name:string|null;last_name:string|null;nickname:string|null};
type Entry={id:number;player_id:number;reason:string|null;type:"beer"|"money"|"custom";value:string|null;created_at:string;due_date:string|null;resolved_at:string|null;notes:string|null;escalation_after_days:number|null;escalation_value:string|null};
function playerName(p:Player){return p.nickname?.trim()||[p.first_name,p.last_name].filter(Boolean).join(" ")||p.name||`Spieler ${p.id}`;}
function date(v:string|null){return v?new Date(v).toLocaleDateString("de-DE"):"—";}
function escalationDate(e:Entry){const d=new Date(e.created_at);d.setDate(d.getDate()+(e.escalation_after_days??28));return d;}
function isEscalated(e:Entry){return !e.resolved_at && !!e.escalation_value && Date.now()>=escalationDate(e).getTime();}

export default async function Page({searchParams}:Props){
 const query=await searchParams; const {clubId,membership,isPowerUser}=await requireClub(); if(!canManageClub({isPowerUser,role:membership.role})) redirect("/admin"); const flags=await getFeatureFlagsForClub(clubId); if(!(flags.penalties??false)) redirect("/admin"); const supabase=await createClient();
 const [{data:playersData},{data:entriesData}]=await Promise.all([supabase.from("players").select("id,name,first_name,last_name,nickname").eq("club_id",clubId).eq("is_guest",false).eq("is_active",true).order("first_name"),supabase.from("penalties").select("id,player_id,reason,type,value,created_at,due_date,resolved_at,notes,escalation_after_days,escalation_value").eq("club_id",clubId).order("created_at",{ascending:false})]);
 const players=(playersData??[]) as Player[]; const entries=(entriesData??[]) as Entry[]; const names=new Map(players.map(p=>[p.id,playerName(p)])); const open=entries.filter(e=>!e.resolved_at); const done=entries.filter(e=>e.resolved_at); const money=open.filter(e=>e.type==="money").reduce((sum,e)=>sum+(Number((e.value??"").replace("€","").replace(",",".").trim())||0),0);
 return <main className="min-h-screen bg-neutral-100"><section className="mx-auto max-w-4xl space-y-4 px-4 py-5">
  <Link href="/admin" className="text-sm font-semibold text-slate-600">← Adminbereich</Link>
  <div className="rounded-[26px] bg-slate-950 p-5 text-white shadow-sm"><div className="text-xs font-bold uppercase tracking-[.2em] text-white/50">Teamleben</div><h1 className="mt-1 text-2xl font-black">💰 Mannschaftskasse</h1><p className="mt-2 text-sm text-white/70">Kleine Beträge, Kisten und die wichtigen Regeln des Mannschaftslebens.</p><div className="mt-4 flex gap-2"><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold">{open.length} offen</span><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold">{money.toFixed(2).replace(".",",")} € offen</span></div></div>
  {query?.saved==="1"?<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">Mannschaftskasse aktualisiert.</div>:null}{query?.error?<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{query.error}</div>:null}
  <div className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Neuer Posten</h2><form action={addPenaltyAction} className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><select name="player_id" required className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><option value="">Spieler wählen</option>{players.map(p=><option key={p.id} value={p.id}>{playerName(p)}</option>)}</select><select name="preset" defaultValue="" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><option value="">Eigener Posten</option><option value="missed_penalty">⚽ Elfer verschossen · Kiste Bier</option><option value="birthday">🎂 Geburtstag · Kiste Bier</option><option value="no_show">👻 Zugesagt, nicht gekommen · Kiste Bier</option><option value="late">⏰ Zugesagt, zu spät · 0,50 €</option><option value="walk_in">🥷 Nicht zugesagt, gekommen · 0,50 €</option></select></div><div className="grid gap-3 sm:grid-cols-3"><input name="reason" placeholder="Eigener Grund" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/><select name="type" defaultValue="beer" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><option value="beer">Sachposten</option><option value="money">Geld</option><option value="custom">Sonstiges</option></select><input name="value" placeholder="z. B. Kuchen / 2 €" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/></div><input name="notes" placeholder="Notiz (optional)" className="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Posten eintragen</button></form><p className="mt-3 text-xs text-slate-500">Kisten-Regel: nach 4 Wochen offen → + 1 Sechserträger. 🍻</p></div>
  <div className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Offene Posten</h2><div className="mt-4 space-y-3">{open.length===0?<div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Alles beglichen. Verdächtig vorbildlich. 😄</div>:open.map(e=><div key={e.id} className={`rounded-2xl border p-4 ${isEscalated(e)?"border-amber-300 bg-amber-50":"border-slate-200"}`}><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><div className="font-bold">{names.get(e.player_id)??`Spieler ${e.player_id}`}</div><div className="mt-1 text-sm text-slate-600">{e.reason||"Ohne Grund"} · <b>{e.value||"Posten"}</b></div><div className="mt-1 text-xs text-slate-500">Seit {date(e.created_at)}{e.escalation_value?` · Aufschlag ab ${escalationDate(e).toLocaleDateString("de-DE")}`:""}</div>{isEscalated(e)?<div className="mt-2 text-sm font-black text-amber-800">🍻 Überfällig: {e.escalation_value}</div>:null}</div><div className="flex gap-2"><form action={resolvePenaltyAction}><input type="hidden" name="penalty_id" value={e.id}/><button className="rounded-lg bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-700">Beglichen ✓</button></form><form action={deletePenaltyAction}><input type="hidden" name="penalty_id" value={e.id}/><button className="rounded-lg bg-red-50 px-3 py-2 text-sm font-bold text-red-700">Löschen</button></form></div></div></div>)}</div></div>
  {done.length?<details className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer font-black">Beglichen ({done.length})</summary><div className="mt-4 space-y-2">{done.map(e=><div key={e.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm"><div><b>{names.get(e.player_id)??e.player_id}</b> · {e.reason} · {e.value}</div><form action={reopenPenaltyAction}><input type="hidden" name="penalty_id" value={e.id}/><button className="text-xs font-bold">Wieder öffnen</button></form></div>)}</div></details>:null}
 </section></main>;
}
