import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getAuthContext } from "@/lib/auth/context";
import { AUTH_ROUTES } from "@/lib/auth/routes";
import { getFeatureFlagsForClub } from "@/lib/feature-flags";
import ProfileForm from "./ProfileForm";
import ProfilePasswordForm from "./ProfilePasswordForm";
import PushPreferencesForm from "./PushPreferencesForm";
import {createAbsenceAction,deleteAbsenceAction} from "./absence-actions";
type ProfilePageProps={searchParams?:Promise<{account_delete_error?:string;absence_saved?:string;absence_error?:string}>};type ClubRow={id:string;display_name:string|null;name:string|null};type Absence={id:number;start_date:string;end_date:string;reason:string;note:string|null};
function getClubLabel(c:ClubRow|null|undefined){return c?.display_name??c?.name??null;}function reasonLabel(r:string){return r==="vacation"?"🏖️ Urlaub":r==="injured"?"🤕 Verletzt":r==="sick"?"🤒 Krank":"⏸️ Sonstiges";}function de(d:string){const [y,m,x]=d.split("-");return `${x}.${m}.${y}`;}function getAccountDeleteErrorMessage(e?:string){switch(e){case"confirmation":return'Bitte gib exakt „KONTO LÖSCHEN“ ein und bestätige die Checkbox.';case"sole_admin":return"Du bist noch alleiniger Admin eines Clubs. Übertrage zuerst die Admin-Rolle oder lösche den Club.";case"delete_failed":return"Dein Konto konnte nicht vollständig gelöscht werden. Bitte versuche es erneut.";default:return"";}}
export default async function ProfilePage({searchParams}:ProfilePageProps){const q=await searchParams;const ctx=await getAuthContext();if(!ctx.user)redirect(AUTH_ROUTES.login);const supabase=await createClient();let activeClubName:string|null=null;if(ctx.activeClubId){const{data:club}=await supabase.from("clubs").select("id, display_name, name").eq("id",ctx.activeClubId).maybeSingle<ClubRow>();activeClubName=getClubLabel(club);}const membership=ctx.memberships.find(m=>m.club_id===ctx.activeClubId)??ctx.memberships[0]??null;const role=membership?.role??"member";const flags=ctx.activeClubId?await getFeatureFlagsForClub(ctx.activeClubId):null;const accountDeleteError=getAccountDeleteErrorMessage(q?.account_delete_error);let absences:Absence[]=[];if(ctx.player&&ctx.activeClubId){const{data}=await supabase.from("player_absences").select("id,start_date,end_date,reason,note").eq("club_id",ctx.activeClubId).eq("player_id",ctx.player.id).gte("end_date",new Date().toISOString().slice(0,10)).order("start_date");absences=(data??[]) as Absence[];}
return <main className="mx-auto flex w-full max-w-3xl flex-col gap-6 px-4 py-6 sm:px-6">
{ctx.player?<Link href={`/players/${ctx.player.id}`} className="group rounded-[28px] border border-stone-300 bg-[#f4f2e9] p-5 shadow-sm"><div className="flex justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.22em] text-slate-500">strikr · digital</div><div className="mt-1 text-2xl font-black">Mein Spielerpass</div><p className="mt-1 text-sm text-slate-600">Foto, Geburtstag, Position & Rückennummer</p></div><div className="rounded-xl border border-stone-300 bg-white/60 px-3 py-2 text-right text-[10px] font-mono">PASS-NR.<br/><b>STR-{String(ctx.player.id).padStart(5,"0")}</b></div></div><div className="mt-4 text-sm font-black">Spielerpass öffnen →</div></Link>:null}
{ctx.player?<section className="rounded-[28px] border border-blue-200 bg-white p-5 shadow-sm"><div className="text-[10px] font-black uppercase tracking-[.2em] text-blue-600">Meine Trainings</div><h2 className="mt-1 text-xl font-black">🏖️ Abwesenheit eintragen</h2><p className="mt-1 text-sm text-slate-600">Urlaub, Verletzung oder Krankheit: Alle Einheiten im Zeitraum werden automatisch abgesagt.</p>{q?.absence_saved!==undefined?<div className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">Gespeichert · {q.absence_saved} Einheit{q.absence_saved==="1"?"":"en"} abgesagt.</div>:null}{q?.absence_error?<div className="mt-3 rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-800">{q.absence_error}</div>:null}<form action={createAbsenceAction} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Von<input name="start_date" type="date" required className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/></label><label className="text-xs font-bold text-slate-600">Bis einschließlich<input name="end_date" type="date" required className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/></label><select name="reason" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><option value="vacation">🏖️ Urlaub</option><option value="injured">🤕 Verletzt</option><option value="sick">🤒 Krank</option><option value="other">⏸️ Sonstiges</option></select><input name="note" placeholder="Notiz (optional)" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/><button className="sm:col-span-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-black text-white">Zeitraum absagen</button></form>{absences.length?<div className="mt-5 space-y-2"><div className="text-xs font-black uppercase tracking-wide text-slate-400">Geplante Abwesenheiten</div>{absences.map(a=><div key={a.id} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><div className="text-sm font-black">{reasonLabel(a.reason)}</div><div className="text-xs text-slate-500">{de(a.start_date)} – {de(a.end_date)}{a.note?` · ${a.note}`:""}</div></div><form action={deleteAbsenceAction}><input type="hidden" name="absence_id" value={a.id}/><button className="text-xs font-bold text-rose-600">Eintrag löschen</button></form></div>)}</div>:null}<p className="mt-3 text-[11px] text-slate-400">Hinweis: Löschen entfernt den Abwesenheitseintrag, bereits gesetzte Absagen bleiben bestehen und können bei der jeweiligen Einheit geändert werden.</p></section>:null}
{flags?.penalties?<Link href="/mannschaftskasse" className="rounded-[28px] bg-slate-950 p-5 text-white shadow-sm"><div className="text-[10px] font-black uppercase tracking-[.2em] text-white/50">Teamleben</div><div className="mt-1 text-xl font-black">💰 Mannschaftskasse</div><p className="mt-1 text-sm text-white/70">Offene Posten sehen oder direkt einen neuen melden.</p></Link>:null}<ProfileForm player={ctx.player} email={ctx.user.email??""} activeClubName={activeClubName} activeClubId={ctx.activeClubId}/>{flags?.hall_of_fame_badges?<Link href="/badges" className="rounded-3xl bg-slate-950 p-6 text-white"><b>Hall of Fame öffnen</b></Link>:null}<PushPreferencesForm/><section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="text-sm font-semibold uppercase text-slate-500">Konto</h2><div className="mt-3 text-sm">{activeClubName??"Kein aktiver Club"} · {role} · {ctx.user.email??"—"}</div></section><ProfilePasswordForm email={ctx.user.email??""}/><section className="rounded-3xl border border-rose-200 bg-white p-6"><h2 className="text-xl font-extrabold">Konto dauerhaft löschen</h2>{accountDeleteError?<div className="mt-4 text-sm text-rose-700">{accountDeleteError}</div>:null}<form method="post" action="/api/account/delete" className="mt-5 space-y-4"><input name="confirmation" className="w-full rounded-xl border px-3 py-2.5" placeholder="KONTO LÖSCHEN"/><label className="flex gap-2 text-sm"><input type="checkbox" name="acknowledgement" value="1"/> Vorgang kann nicht rückgängig gemacht werden.</label><button className="rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-bold text-white">Konto dauerhaft löschen</button></form></section></main>}
