alter table public.club_settings
  add column if not exists work_duty_target_minutes integer not null default 0;

alter table public.club_settings
  drop constraint if exists club_settings_work_duty_target_minutes_check;

alter table public.club_settings
  add constraint club_settings_work_duty_target_minutes_check
  check (work_duty_target_minutes between 0 and 60000);

create table if not exists public.work_duty_events (
  id bigint generated by default as identity primary key,
  club_id uuid not null references public.clubs(id) on delete cascade,
  title text not null check (char_length(trim(title)) between 2 and 120),
  event_date date not null,
  location text null,
  notes text null,
  created_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.work_duty_shifts (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.work_duty_events(id) on delete cascade,
  club_id uuid not null references public.clubs(id) on delete cascade,
  label text not null check (char_length(trim(label)) between 1 and 120),
  start_time time not null,
  end_time time not null,
  capacity integer not null default 1 check (capacity between 1 and 50),
  created_at timestamptz not null default now(),
  constraint work_duty_shift_time_check check (end_time > start_time)
);

create table if not exists public.work_duty_signups (
  id bigint generated by default as identity primary key,
  shift_id bigint not null references public.work_duty_shifts(id) on delete cascade,
  club_id uuid not null references public.clubs(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  credited_minutes integer null check (credited_minutes is null or credited_minutes between 0 and 1440),
  completed boolean not null default false,
  signed_up_at timestamptz not null default now(),
  unique (shift_id, player_id)
);

create index if not exists work_duty_events_club_date_idx
  on public.work_duty_events (club_id, event_date);

create index if not exists work_duty_shifts_club_event_idx
  on public.work_duty_shifts (club_id, event_id);

create index if not exists work_duty_signups_club_player_idx
  on public.work_duty_signups (club_id, player_id);

alter table public.work_duty_events enable row level security;
alter table public.work_duty_shifts enable row level security;
alter table public.work_duty_signups enable row level security;

drop policy if exists "work_duty_events_select_members" on public.work_duty_events;
create policy "work_duty_events_select_members"
on public.work_duty_events for select
using (
  exists (
    select 1 from public.club_memberships cm
    where cm.club_id = work_duty_events.club_id
      and cm.user_id = auth.uid()
  )
);

drop policy if exists "work_duty_events_admin_write" on public.work_duty_events;
create policy "work_duty_events_admin_write"
on public.work_duty_events for all
using (
  exists (
    select 1 from public.club_memberships cm
    where cm.club_id = work_duty_events.club_id
      and cm.user_id = auth.uid()
      and cm.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.club_memberships cm
    where cm.club_id = work_duty_events.club_id
      and cm.user_id = auth.uid()
      and cm.role = 'admin'
  )
);

drop policy if exists "work_duty_shifts_select_members" on public.work_duty_shifts;
create policy "work_duty_shifts_select_members"
on public.work_duty_shifts for select
using (
  exists (
    select 1 from public.club_memberships cm
    where cm.club_id = work_duty_shifts.club_id
      and cm.user_id = auth.uid()
  )
);

drop policy if exists "work_duty_shifts_admin_write" on public.work_duty_shifts;
create policy "work_duty_shifts_admin_write"
on public.work_duty_shifts for all
using (
  exists (
    select 1 from public.club_memberships cm
    where cm.club_id = work_duty_shifts.club_id
      and cm.user_id = auth.uid()
      and cm.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.club_memberships cm
    where cm.club_id = work_duty_shifts.club_id
      and cm.user_id = auth.uid()
      and cm.role = 'admin'
  )
);

drop policy if exists "work_duty_signups_select_members" on public.work_duty_signups;
create policy "work_duty_signups_select_members"
on public.work_duty_signups for select
using (
  exists (
    select 1 from public.club_memberships cm
    where cm.club_id = work_duty_signups.club_id
      and cm.user_id = auth.uid()
  )
);

drop policy if exists "work_duty_signups_insert_own" on public.work_duty_signups;
create policy "work_duty_signups_insert_own"
on public.work_duty_signups for insert
with check (
  exists (
    select 1
    from public.players p
    join public.club_memberships cm
      on cm.club_id = p.club_id
     and cm.user_id = auth.uid()
    where p.id = work_duty_signups.player_id
      and p.club_id = work_duty_signups.club_id
      and p.user_id = auth.uid()
  )
);

drop policy if exists "work_duty_signups_delete_own_or_admin" on public.work_duty_signups;
create policy "work_duty_signups_delete_own_or_admin"
on public.work_duty_signups for delete
using (
  exists (
    select 1 from public.players p
    where p.id = work_duty_signups.player_id
      and p.user_id = auth.uid()
  )
  or exists (
    select 1 from public.club_memberships cm
    where cm.club_id = work_duty_signups.club_id
      and cm.user_id = auth.uid()
      and cm.role = 'admin'
  )
);

drop policy if exists "work_duty_signups_admin_update" on public.work_duty_signups;
create policy "work_duty_signups_admin_update"
on public.work_duty_signups for update
using (
  exists (
    select 1 from public.club_memberships cm
    where cm.club_id = work_duty_signups.club_id
      and cm.user_id = auth.uid()
      and cm.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.club_memberships cm
    where cm.club_id = work_duty_signups.club_id
      and cm.user_id = auth.uid()
      and cm.role = 'admin'
  )
);

comment on table public.work_duty_events is 'Arbeitsdienst-Termine je Club.';
comment on table public.work_duty_shifts is 'Einzelne Arbeitsdienst-Schichten mit Kapazität.';
comment on table public.work_duty_signups is 'Spieler-Eintragungen und gutgeschriebene Arbeitsminuten.';
