create table if not exists public.landing_page_visits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  path text not null default '/',
  referrer text,
  referrer_host text,

  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,

  country_code text,
  device_type text,
  user_agent_family text,

  app_env text
);

create index if not exists idx_landing_page_visits_created_at
  on public.landing_page_visits (created_at desc);

create index if not exists idx_landing_page_visits_utm_source
  on public.landing_page_visits (utm_source);

create index if not exists idx_landing_page_visits_referrer_host
  on public.landing_page_visits (referrer_host);

alter table public.landing_page_visits enable row level security;

comment on table public.landing_page_visits is
  'Privacy-conscious landing page analytics events. No IP addresses or names are stored.';
