create table if not exists public.landing_page_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  event_name text not null,
  path text not null default '/',

  utm_source text,
  utm_medium text,
  utm_campaign text,
  referrer text,
  referrer_host text,

  country_code text,
  device_type text,
  user_agent_family text,

  app_env text
);

create index if not exists idx_landing_page_events_created_at
  on public.landing_page_events (created_at desc);

create index if not exists idx_landing_page_events_event_name
  on public.landing_page_events (event_name);

create index if not exists idx_landing_page_events_utm_source
  on public.landing_page_events (utm_source);

alter table public.landing_page_events enable row level security;

comment on table public.landing_page_events is
  'Privacy-conscious landing page conversion events. No IP addresses or names are stored.';
