alter table public.club_settings
  add column if not exists beerkasse_premium_enabled boolean not null default false,
  add column if not exists beerkasse_price_cents integer not null default 200,
  add column if not exists beerkasse_stats_enabled boolean not null default true,
  add column if not exists beerkasse_badges_enabled boolean not null default true;

alter table public.club_settings
  drop constraint if exists club_settings_beerkasse_price_cents_check;

alter table public.club_settings
  add constraint club_settings_beerkasse_price_cents_check
  check (beerkasse_price_cents between 1 and 100000);

-- Bestehende aktive Bierkassen behalten ihren Zugriff.
update public.club_settings
set beerkasse_premium_enabled = true
where beerkasse_enabled = true
  and beerkasse_premium_enabled = false;

create table if not exists public.beer_consumptions (
  id bigint generated by default as identity primary key,
  club_id uuid not null references public.clubs(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  quantity integer not null check (quantity between 1 and 99),
  unit_price_cents integer not null check (unit_price_cents between 1 and 100000),
  total_cents integer not null check (total_cents between 1 and 9900000),
  created_at timestamptz not null default now()
);

create index if not exists beer_consumptions_club_created_idx
  on public.beer_consumptions (club_id, created_at desc);

create index if not exists beer_consumptions_club_player_idx
  on public.beer_consumptions (club_id, player_id);

alter table public.beer_consumptions enable row level security;

drop policy if exists "beer_consumptions_select_members" on public.beer_consumptions;
create policy "beer_consumptions_select_members"
on public.beer_consumptions
for select
using (
  exists (
    select 1
    from public.club_memberships cm
    where cm.club_id = beer_consumptions.club_id
      and cm.user_id = auth.uid()
  )
);

drop policy if exists "beer_consumptions_insert_own" on public.beer_consumptions;
create policy "beer_consumptions_insert_own"
on public.beer_consumptions
for insert
with check (
  exists (
    select 1
    from public.players p
    join public.club_memberships cm
      on cm.club_id = p.club_id
     and cm.user_id = auth.uid()
    where p.id = beer_consumptions.player_id
      and p.club_id = beer_consumptions.club_id
      and p.user_id = auth.uid()
  )
);

comment on table public.beer_consumptions is
'Optionale Bierkasse+-Verbrauchsbuchungen pro Club und Spieler. Dient der Bierstatistik; die Zahlung selbst läuft extern über PayPal.';
