create table if not exists public.team_feed_reactions (
  id bigint generated by default as identity primary key,
  club_id uuid not null references public.clubs(id) on delete cascade,
  feed_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check (
    reaction in (
      'prost',
      'biermaschine',
      'maschine',
      'laeuft',
      'glueckwunsch',
      'kischde',
      'herz'
    )
  ),
  created_at timestamptz not null default now()
);

alter table public.team_feed_reactions enable row level security;

create index if not exists team_feed_reactions_feed_idx
  on public.team_feed_reactions (club_id, feed_id);

with ranked as (
  select
    id,
    row_number() over (
      partition by club_id, feed_id, user_id
      order by created_at desc, id desc
    ) as row_no
  from public.team_feed_reactions
)
delete from public.team_feed_reactions reactions
using ranked
where reactions.id = ranked.id
  and ranked.row_no > 1;

alter table public.team_feed_reactions
  drop constraint if exists team_feed_reactions_club_id_feed_id_user_id_reaction_key;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.team_feed_reactions'::regclass
      and conname = 'team_feed_reactions_club_id_feed_id_user_id_key'
  ) then
    alter table public.team_feed_reactions
      add constraint team_feed_reactions_club_id_feed_id_user_id_key
      unique (club_id, feed_id, user_id);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'team_feed_reactions'
      and policyname = 'team feed reactions read club'
  ) then
    create policy "team feed reactions read club"
      on public.team_feed_reactions
      for select
      to authenticated
      using (
        exists (
          select 1
          from public.club_memberships cm
          where cm.club_id = team_feed_reactions.club_id
            and cm.user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'team_feed_reactions'
      and policyname = 'team feed reactions own insert'
  ) then
    create policy "team feed reactions own insert"
      on public.team_feed_reactions
      for insert
      to authenticated
      with check (
        user_id = auth.uid()
        and exists (
          select 1
          from public.club_memberships cm
          where cm.club_id = team_feed_reactions.club_id
            and cm.user_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'team_feed_reactions'
      and policyname = 'team feed reactions own delete'
  ) then
    create policy "team feed reactions own delete"
      on public.team_feed_reactions
      for delete
      to authenticated
      using (user_id = auth.uid());
  end if;
end
$$;

grant select, insert, delete on public.team_feed_reactions to authenticated;
grant usage, select on sequence public.team_feed_reactions_id_seq to authenticated;
