create table if not exists public.player_absences (
  id bigint generated by default as identity primary key,
  club_id uuid not null references public.clubs(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  reason text not null default 'other',
  note text,
  created_at timestamptz not null default now(),
  constraint player_absences_date_order check (end_date >= start_date)
);
create index if not exists player_absences_club_player_dates_idx on public.player_absences(club_id, player_id, start_date, end_date);
