alter table public.sessions
  add column if not exists session_mode text not null default 'normal',
  add column if not exists tournament_team_count integer,
  add column if not exists tournament_match_minutes integer,
  add column if not exists tournament_winner_team_id bigint,
  add column if not exists tournament_completed_at timestamptz;

alter table public.sessions
  drop constraint if exists sessions_session_mode_check;

alter table public.sessions
  add constraint sessions_session_mode_check
  check (session_mode in ('normal', 'tournament'));

alter table public.sessions
  drop constraint if exists sessions_tournament_team_count_check;

alter table public.sessions
  add constraint sessions_tournament_team_count_check
  check (tournament_team_count is null or tournament_team_count between 2 and 6);

alter table public.sessions
  drop constraint if exists sessions_tournament_match_minutes_check;

alter table public.sessions
  add constraint sessions_tournament_match_minutes_check
  check (tournament_match_minutes is null or tournament_match_minutes between 1 and 60);

create table if not exists public.tournament_matches (
  id bigint generated by default as identity primary key,
  club_id uuid not null references public.clubs(id) on delete cascade,
  session_id bigint not null references public.sessions(id) on delete cascade,
  game_no integer not null,
  team_a_id bigint not null references public.teams(id) on delete cascade,
  team_b_id bigint not null references public.teams(id) on delete cascade,
  goals_team_a integer,
  goals_team_b integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tournament_matches_game_no_positive check (game_no >= 1),
  constraint tournament_matches_goals_nonnegative check (
    (goals_team_a is null or goals_team_a >= 0)
    and (goals_team_b is null or goals_team_b >= 0)
  ),
  constraint tournament_matches_different_teams check (team_a_id <> team_b_id)
);

create unique index if not exists idx_tournament_matches_session_game
  on public.tournament_matches (session_id, game_no);

create index if not exists idx_tournament_matches_club_session
  on public.tournament_matches (club_id, session_id);

alter table public.tournament_matches enable row level security;

revoke all on table public.tournament_matches from anon, authenticated;
grant all on table public.tournament_matches to service_role;
grant usage, select on sequence public.tournament_matches_id_seq to service_role;
