create table if not exists public.product_analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid null,
  club_id uuid null references public.clubs(id) on delete set null,
  event_name text not null,
  path text null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists product_analytics_events_created_at_idx
  on public.product_analytics_events(created_at desc);
create index if not exists product_analytics_events_event_name_idx
  on public.product_analytics_events(event_name);
create index if not exists product_analytics_events_club_id_idx
  on public.product_analytics_events(club_id);

alter table public.product_analytics_events enable row level security;
revoke all on public.product_analytics_events from anon, authenticated;
