create table if not exists public.club_chat_messages (
  id bigint generated by default as identity primary key,
  club_id uuid not null references public.clubs(id) on delete cascade,
  user_id uuid not null,
  player_id bigint references public.players(id) on delete set null,
  author_name text not null,
  body text not null,
  created_at timestamptz not null default now(),
  constraint club_chat_messages_body_length check (
    char_length(btrim(body)) between 1 and 500
  )
);

create index if not exists club_chat_messages_club_created_idx
  on public.club_chat_messages (club_id, created_at desc, id desc);

alter table public.club_chat_messages enable row level security;

drop policy if exists club_chat_messages_select_member on public.club_chat_messages;
create policy club_chat_messages_select_member
on public.club_chat_messages
for select
to authenticated
using (public.is_member_of_club(club_id));

drop policy if exists club_chat_messages_insert_member on public.club_chat_messages;
create policy club_chat_messages_insert_member
on public.club_chat_messages
for insert
to authenticated
with check (
  public.is_member_of_club(club_id)
  and user_id = auth.uid()
);

drop policy if exists club_chat_messages_delete_own_or_admin on public.club_chat_messages;
create policy club_chat_messages_delete_own_or_admin
on public.club_chat_messages
for delete
to authenticated
using (
  user_id = auth.uid()
  or public.is_admin_of_club(club_id)
);
